title: Quantum Optimization Group
email: wolfgang.lechner@uibk.ac.at
description: > 
  Quantum Computing, Quantum Optimization, Adiabatic Quantum Computing
baseurl: "" 
url: "" 

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  
include: ["_people"]